### ISSUE TITLE
Why use pydantic's mypy plugin with typer?

### ISSUE THREAD

**Issue by JonathanPlasse** [radix-ai/poetry-cookiecutter#127]
> Pydantic is a library to handle data validation using standard modern Python type annotations.
> It powers FastAPI underneath.
> It is not used by Typer, but it inspired a lot of the design (through FastAPI).[^1]

It also does not support models.[^2]
[^1]: [Reference](https://typer.tiangolo.com/alternatives/#pydantic)
[^2]: [Reference](https://github.com/tiangolo/typer/issues/111)

**Comment by lsorber** [comment]
Hi @JonathanPlasse, yes I think you're right. The reason Pydantic is enabled with Typer is because we use Pydantic with Typer, but that's wouldn't necessarily be true in general. We'll address it in an upcoming PR!

**Comment by lsorber** [comment]
Solved with #131!
