### ISSUE TITLE
package_url vs private_package_repository_url

### ISSUE THREAD

**Issue by chanansh** [radix-ai/poetry-cookiecutter#164]
what is the different between these parameters?
how can I update the project later with a new url?
Do you know which url should I put for a private gitlab in the project?
It's not clear from gitlab documentation. It supposed to be `https://gitlab.example.com/api/v4/projects/<project_id>/packages/pypi` but that does not work.

**Comment by lsorber** [comment]
See the `Template parameters` section of the README [1].

To answer your questions:
1. `package_url` should be the URL to your repository, e.g. `https://gitlab.com/{username}/{project_name}`
2. `private_package_repository_url` should be of the form `https://gitlab.com/api/v4/projects/{project_id}/packages/pypi/simple` for GitLab. You can find the `project_id` just below your GitLab project's name if you go to the `package_url`.

[1] https://github.com/radix-ai/poetry-cookiecutter#-template-parameters

**Comment by chanansh** [comment]
how can I edit those AFTER the project was created with cookiecutter?

**Comment by lsorber** [comment]
For those two parameters, all you need to do is a find & replace of the previous value and the new value across your project (make sure to replace all instances of the old value with the new value, including e.g. in `.cruft.json`!).

**Comment by lsorber** [comment]
Closing this as I assume it is resolved.
