### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by chanansh** [radix-ai/poetry-cookiecutter#166]
I have created a clean project (no user files).
I created a Gitlab Runner to run it.
But, the pipeline breaks.

Using Docker executor with image private_gitlab_server.com:5005/my_repo/ci:9a495cbc014c ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image private_gitlab_server.com:5005/my_repo/ci:9a495cbc014c ...
WARNING: Failed to pull image with policy "always": Error response from daemon: manifest for gitlab-private_gitlab_server.com:5005/my_repo/ci:9a495cbc014c not found: manifest unknown: manifest unknown (manager.go:23[7](https://private_gitlab_server.com/my_repo/-/jobs/52751479#L7):0s)
ERROR: Job failed: failed to pull image "private_gitlab_server.com:5005/my_repo/ci:[9](https://private_gitlab_server.com/my_repo/-/jobs/52751479#L9)a495cbc014c" with specified policies [always]: Error response from daemon: manifest for private_gitlab_server.com:5005/my_repo/ci:9a495cbc014c not found: manifest unknown: manifest unknown (manager.go:237:0s)

**Comment by lsorber** [comment]
I don't have any experience with the privately hosted version of GitLab, but it looks like you might need to look into the configuration of your GitLab Registry.

Did the `Compute CI image hash` and the `Build CI image` jobs complete successfully?

**Comment by chanansh** [comment]
I see only two jobs:
![image](https://user-images.githubusercontent.com/5981644/216939128-d257d532-2815-44d2-8e1c-1dc52599306d.png)

**Comment by chanansh** [comment]
so I guess it seems like it skips the build stage

**Comment by lsorber** [comment]
Thanks for sharing. Indeed, looks like the `Build CI image` step was not executed, let me look into that.

**Comment by lsorber** [comment]
Apologies that you're running into this issue. The solution is not as easy as I expected. We'll get it fixed!

**Comment by lsorber** [comment]
Hey @chanash, this should be fixed now. Sorry it took a bit to get it merged!

**Comment by chanansh** [comment]
thanks. checking
