### ISSUE TITLE
AGPL license

### ISSUE THREAD

**Issue by CharlesAntoineParent** [radix-ai/poetry-cookiecutter#208]
Hello,

First of all, I just want to tell you that your cookie-cutter is well-designed and nice to use. I saw that you use an AGPL license and I wanted to know if all projects created with your template must have that license too. In the case of a cookie-cutter, it is not as clear as a simple repository since the cookie-cutter is not used after the project was created. If AGPL must be used, you could add it by default as the license of the template!

Thank you !

**Comment by lsorber** [comment]
Closing assuming the question has been answered.
