### ISSUE TITLE
Rebuild Docker image when Python dependencies have changed

### ISSUE THREAD

**Issue by souliane** [radix-ai/poetry-cookiecutter#212]
If I am not mistaken, the docker image will not be updated by the next build when the dependencies from `poetry.lock` change.
This is problematic because we expect `docker build` or `docker compose build` to produce an up-to-date image, ready to use.

Some people recommend adding this before the concerned `RUN` command (c.f. [stackoverflow](https://stackoverflow.com/questions/35134713/disable-cache-for-specific-run-commands/58801213#58801213)):
```
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
```

Another option would be to pass the MD5 of `poetry.lock` to Dockerfile, so that it rebuilds only when the dependencies actually changed. 

Ideally, we would install the dependencies as late as possible, to re-use as much docker cache as possible.

**Comment by lsorber** [comment]
It's possible that it will copy the layer from cache indeed. Interesting idea to force it to rebuild that layer with that command. Let me look into this a bit and see how we want to improve this.

**Comment by lsorber** [comment]
Hi @souliane, on closer inspection we don't need to do anything: [this line in the Dockerfile will cause the Docker to update all packages when rebuilding the image if poetry.lock has been updated](https://github.com/radix-ai/poetry-cookiecutter/blob/26e2bae35f6215fa9968d6f9406fbf5016c3cfc2/%7B%7B%20cookiecutter.__package_name_kebab_case%20%7D%7D/Dockerfile#L56).

**Comment by souliane** [comment]
Alright... I guess the problem is on my side then :-p
Thanks a lot for looking at it.
