### ISSUE TITLE
Add docker and docker compose to dev container.

### ISSUE THREAD

**Issue by JWuzyk** [radix-ai/poetry-cookiecutter#224]
Docker and docker compose are commonly used in during development activities, e.g. to test changes to the docker image. Currently this requires to user to open a separate terminal to run docker commands, then switch back to VS Code to make changes. 

I suggest adding docker and docker compose to the dev container. This is a relatively simple addition but complex to figure out the first time one needs to do it.

This would also further align the dev and deployment experiences, e.g. a developer can more easily test the api with `docker compose up api` instead of `poe serve`.

**Comment by lsorber** [comment]
As discussed, we'd try this out with a PR to evaluate:
- How much complexity it would add to the Dockerfile
- The impact on the build times
- The impact on the image size
- The extend to which this could be a footgun w.r.t. file creation on hosted volumes

**Comment by JWuzyk** [comment]
After attempting to do this in practice, I realised that my previous approach relied on having root access in the container.

Specifically the user in the container would need permission to write to the docker socket (/var/run/docker.sock) owned by root.

Considering this and the further user complications this feature entails, I'll make with as closed.

**Comment by lsorber** [comment]
Perhaps it is doable by installing rootless docker instead (which is a best practice anyway)?
